# Generated by Django 4.1.3 on 2022-12-07 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_rate_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='student',
            new_name='id_student',
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='teacher',
            new_name='id_teacher',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='user',
            new_name='id_user',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='user',
            new_name='id_user',
        ),
    ]
