# Generated by Django 4.1.3 on 2022-12-13 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_student_rate_id_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='city',
            field=models.CharField(default='Da Nang', max_length=20),
        ),
        migrations.CreateModel(
            name='InformationClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_lop', models.CharField(max_length=50, unique=True)),
                ('lop', models.IntegerField(default=2)),
                ('hoc_phi', models.CharField(max_length=10)),
                ('mo_ta', models.CharField(max_length=100)),
                ('thoi_gian', models.FloatField(default=2)),
                ('buoi', models.CharField(max_length=50)),
                ('id_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.teacher')),
            ],
        ),
    ]
